name: s98-nanopi-neo-plus2
version: 16.04-0.1
summary: Nanopi Neo Plus2 support package
description: |
 Support files for booting the Nanopi Neo Plus2
type: gadget
architectures:
  - arm64
confinement: strict
grade: stable
parts:
  atf:
    plugin: nil
    source: https://github.com/apritzel/arm-trusted-firmware
    source-type: git
    source-branch: allwinner
    build: |
      if [ "$(arch)" = "x86_64" ]; then
        export CROSS_COMPILE=aarch64-linux-gnu-
      fi
      make PLAT=sun50iw1p1 bl31
    build-attributes: [no-install]
  u-boot:
    plugin: uboot
    source: git://git.denx.de/u-boot.git
    source-branch: v2018.01
    kdefconfig: 
      - nanopi_neo_plus2_ucore_defconfig
    -arch: arm
    build-packages: [device-tree-compiler, libfdt-dev, python-dev, curl, swig]
    after: [atf]
    prepare: |
      git apply ../../../uboot-*.patch
      ln -s ../../atf/build/build/sun50iw1p1/release/bl31.bin .
      ln -s ../../../../nanopi_neo_plus2_ucore_defconfig configs/
    install: |
      cat spl/sunxi-spl.bin u-boot.itb > $SNAPCRAFT_PART_INSTALL/u-boot-sunxi-with-spl.bin
      tools/mkenvimage -r -s 131072  -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      ln -s uboot.env $SNAPCRAFT_PART_INSTALL/uboot.conf
slots:
  bcm-gpio-3:
    interface: gpio
    number: 12
  bcm-gpio-5:
    interface: gpio
    number: 11
  bcm-gpio-7:
    interface: gpio
    number: 203
  bcm-gpio-8:
    interface: gpio
    number: 198
  bcm-gpio-10:
    interface: gpio
    number: 199
  bcm-gpio-11:
    interface: gpio
    number: 0
  bcm-gpio-12:
    interface: gpio
    number: 6
  bcm-gpio-13:
    interface: gpio
    number: 2
  bcm-gpio-15:
    interface: gpio
    number: 3
  bcm-gpio-16:
    interface: gpio
    number: 200
  bcm-gpio-18:
    interface: gpio
    number: 201
  bcm-gpio-19:
    interface: gpio
    number: 64
  bcm-gpio-21:
    interface: gpio
    number: 65
  bcm-gpio-22:
    interface: gpio
    number: 1
  bcm-gpio-23:
    interface: gpio
    number: 66
  bcm-gpio-24:
    interface: gpio
    number: 67
  i2c-0:
    interface: i2c
    path: /dev/i2c-0
  i2c-1:
    interface: i2c
    path: /dev/i2c-1
  i2c-2:
    interface: i2c
    path: /dev/i2c-2
  i2c-3:
    interface: i2c
    path: /dev/i2c-3
  serialtty-2:
    interface: serial-port
    path: /dev/ttyS2
  bt-serial:
    interface: serial-port
    path: /dev/ttyS3
  spi-0:
    interface: spi
    path: /dev/spidev0.0
